import sys, os, random, math
from collections import deque

#CONSTANTS

CELL_ORDER = 2
BOOSTING_FACTOR = 2
CELLS_PER_COLUMN = 4
INPUT_COVERAGE = 3
PERMANENCE_THRESHOLD = 0.2
PERMANENCE_INC = 0.01
PERMANENCE_DEC = 0.01
DISTAL_SEGMENTS_PER_COLUMN = 12
MIN_OVERLAP = 3
DESIRED_LOCAL_ACTIVITY = 5
INITIAL_INHIBITION_RADIUS = 10
DECAY_RATE = (999.0/1000.0)
BOOST_INCREMENT = 0.1
DISTAL_ACTIVATION_THRESHOLD = 2
MIN_DISTAL_ACTIVATION_THRESHOLD = 1
NEW_SYNAPSE_COUNT = 5
PREVIOUS_TIME_STEP = 1
CURRENT_TIME_STEP = 0